### ISSUE TITLE
Could you help to set this up on Mac?

### ISSUE THREAD

**Issue by agodatt** [berlius/DeepLearningDockerfile#3]
Hello Berlius, 

I am having troubles setting up this Malmo project on my Mac. I get the following error message after running the command:

...:Microsoft-malmo scenarios$ sudo docker build -t berlius/microsoft-malmo:cpu -f Dockerfile .
...
Status: Downloaded newer image for berlius/artificial-intelligence-gpu:latest
 ---> 1f949e1a7ddf
Step 2 : MAINTAINER berlius berlius52@yahoo.com
 ---> Running in 78cc58c66f73
 ---> be9055d58c8a
Removing intermediate container 78cc58c66f73
Step 3 : RUN add-apt-repository ppa:openjdk-r/ppa
 ---> Running in f22617b7194c
Cannot add PPA: 'ppa:openjdk-r/ppa'.
Please check that the PPA name or format is correct.
The command '/bin/sh -c add-apt-repository ppa:openjdk-r/ppa' returned a non-zero code: 1

**Comment by berlius** [comment]
Hello agodatt,

ca-certificates does not appear to be properly installed.

type in the terminal :

sudo apt-get install --reinstall ca-certificates

or, may be, you are working behind a proxy ?

if you fail you can download the container from dockerhub

docker pull berlius/microsoft-malmo

you find attached the "install.log"
[install.txt](https://github.com/berlius/DeepLearningDockerfile/files/440380/install.txt)

**Comment by berlius** [comment]
sorry but my explanation is not clear

sudo apt-get install --reinstall ca-certificates

must be typed into your terminal. Note the presense of "sudo" before

the file "Dockerfile" is, of course,  correct. It should not be changed

the rest of the response is good

**Comment by agodatt** [comment]
Thank you Berlius. I got much further this time, but got an error message again. Let me list what I did:
0. extended the Dockerfile as you proposed in your first response
1. I built for cpu with: sudo docker build -t berlius/microsoft-malmo:cpu -f Dockerfile .
2. shoot up the image with: sudo docker run -it -p 8888:8888 -p 6006:6006 -p 8000:8000 -v `pwd`:/root/sharedfolder  --privileged --device=/dev/snd:/dev/snd -v /tmp/.X11-unix:/tmp/.X11-unix:ro -e DISPLAY=unix$DISPLAY berlius/microsoft-malmo:cpu bash
3. Ran ./launchclient.sh and after a long wait I got this error message: 

Please advise!
Thank you,
agodatt

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.7/userguide/gradle_daemon.html

---

 Powered By MCP:  
 http://modcoderpack.com/  
 Searge, ProfMobius, Fesh0r, 
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : 9.10

---

Version string 'unspecified' does not match SemVer specification 
You should try SemVer : http://semver.org/
:deobfCompileDummyTask
:deobfProvidedDummyTask
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:copyModToClient
:copyModToServer
:deleteSchemas
:copySchemas
:jaxb UP-TO-DATE
:sourceMainJava UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar
:getVersionJson
:extractNatives SKIPPED
:extractUserdev UP-TO-DATE
:getAssetIndex UP-TO-DATE
:getAssets
Current status: 441/734   60%
Current status: 733/734   99%
:makeStart SKIPPED
:runClient
[19:51:01] [main/INFO] [GradleStart]: Extra: []
[19:51:01] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --assetsDir, /root/.gradle/caches/minecraft/assets, --assetIndex, 1.8, --accessToken{REDACTED}, --version, 1.8, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker]
[19:51:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:51:01] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:51:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[19:51:01] [main/INFO] [FML]: Forge Mod Loader version 11.14.3.1543 for Minecraft 1.8 loading
[19:51:01] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_91, running on Linux:amd64:4.4.15-moby, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
[19:51:01] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[19:51:01] [main/INFO] [FML]: Found a command line coremod : com.microsoft.Malmo.OverclockingPlugin
[19:51:01] [main/WARN] [FML]: The coremod com.microsoft.Malmo.OverclockingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:51:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:51:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:51:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:51:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:51:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:51:01] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[19:51:02] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[19:51:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:51:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:51:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:51:02] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:51:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:51:02] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[19:51:03] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:transform:52]: MALMO: Attempting to transform MinecraftServer
[19:51:03] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockRenderer:147]: MALMO: Found Minecraft, attempting to transform it
[19:51:03] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockRenderer:153]: MALMO: Found Minecraft.runGameLoop() method, attempting to transform it
[19:51:03] [main/INFO] [STDOUT]: [com.microsoft.Malmo.OverclockingClassTransformer:overclockRenderer:168]: MALMO: Hooked into call to Minecraft.updateDisplay()
[19:51:03] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
    at GradleStart.main(Unknown Source) [start/:?]
Caused by: java.awt.AWTError: Can't connect to X11 window server using 'unix/private/tmp/com.apple.launchd.f772onzZlR/org.macosforge.xquartz:0' as the value 
    at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method) ~[?:1.8.0_91]
    at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65) ~[?:1.8.0_91]
    at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115) ~[?:1.8.0_91]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_91]
    at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74) ~[?:1.8.0_91]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
    at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_91]
Exception in thread "main"  at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103) ~[?:1.8.0_91]
    at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82) ~[?:1.8.0_91]
    at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:126) ~[_91]8.0
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
    at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_91]
    at java.awt.Toolkit$2.run(Toolkit.java:860) ~[?:1.8.0_91]
    at java.awt.Toolkit$2.run(Toolkit.java:855) ~[?:1.8.0_91]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_91]
    at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854) ~[?:1.8.0_91]
    at org.lwjgl.LinuxSysImplementation.<clinit>(LinuxSysImplementation.java:50) ~[lwjgl-2.9.1.jar:?]
    at org.lwjgl.Sys.createImplementation(Sys.java:126) ~[lwjgl-2.9.1.jar:?]
    at org.lwjgl.Sys.<clinit>(Sys.java:111) ~[lwjgl-2.9.1.jar:?]
    at net.minecraft.client.Minecraft.getSystemTime(Unknown Source) ~[Minecraft.class:?]
    at net.minecraft.client.main.Main.main(Unknown Source) ~[Main.class:?]
    ... 12 more
[19:51:03] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[19:51:03] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:51:03] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:51:03] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:51:03] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:498)
[19:51:03] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
[19:51:03] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at GradleStart.main(Unknown Source)
[19:51:03] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[19:51:03] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(Unknown Source)
[19:51:03] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[19:51:03] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Runtime.exit(Runtime.java:107)
[19:51:03] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.System.exit(System.java:971)
[19:51:03] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[19:51:03] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:51:03] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 6 more
:runClient FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':runClient'.
  
  > Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 24.405 secs
root@d6fe14213778:~/sharedfolder/Malmo-0.15.0-Linux-Ubuntu-14.04-64bit/Minecraft#

**Comment by berlius** [comment]
do you  have a 64 bits Mac OS ?

if the answer is yes you could download the "Mac" version of Malmo at [https://github.com/Microsoft/malmo/releases/download/0.17.0/Malmo-0.17.0-Mac-64bit.zip](https://github.com/Microsoft/malmo/releases/download/0.17.0/Malmo-0.17.0-Mac-64bit.zip)

install the dependancies see [https://github.com/Microsoft/malmo/blob/master/doc/install_macosx.md](https://github.com/Microsoft/malmo/blob/master/doc/install_macosx.md)

and run the client directly without docker and linux

**Comment by berlius** [comment]
the problem seems solved

closing

**Comment by agodatt** [comment]
Thank you for all your help!
Attila Agod
